name: Build and Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -DLUTUM_BUILD_TESTS=ON
          -DLUTUM_BUILD_EDITOR=OFF
          -DLUTUM_ENABLE_RENDERER=OFF
          -DLUTUM_ENABLE_DEBUG_UI=OFF
          -DLUTUM_BUILD_SHADER_TOOLS_FROM_SOURCE=OFF

      - name: Build tests
        run: cmake --build build --config Release --target LutumTests --parallel

      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure